import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class PetService {
  racasCachorro = [
    'Afegão Hound',
    'Affenpinscher',
    'Airedale Terrier',
    'Akita',
    'American Staffordshire Terrier',
    'Basenji',
    'Basset Hound',
    'Beagle',
    'Beagle Harrier',
    'Bearded Collie',
    'Bedlington Terrier',
    'Bichon Frisé',
    'Bloodhound',
    'Bobtail',
    'Boiadeiro Australiano',
    'Boiadeiro Bernês',
    'Border Collie',
    'Border Terrier',
    'Borzoi',
    'Boston Terrier',
    'Boxer',
    'Buldogue Francês',
    'Buldogue Inglês',
    'Bull Terrier',
    'Bulmastife',
    'Cairn Terrier',
    'Cane Corso',
    'Cão de Água Português',
    'Cão de Crista Chinês',
    'Cavalier King Charles Spaniel',
    'Chesapeake Bay Retriever',
    'Chihuahua',
    'Chow Chow',
    'Cocker Spaniel Americano',
    'Cocker Spaniel Inglês',
    'Collie',
    'Coton de Tuléar',
    'Dachshund',
    'Dálmata',
    'Dandie Dinmont Terrier',
    'Dobermann',
    'Dogo Argentino',
    'Dogue Alemão',
    'Fila Brasileiro',
    'Fox Terrier (Pelo Duro e Pelo Liso)',
    'Foxhound Inglês',
    'Galgo Escocês',
    'Galgo Irlandês',
    'Golden Retriever',
    'Grande Boiadeiro Suiço',
    'Greyhound',
    'Grifo da Bélgica',
    'Husky Siberiano',
    'Jack Russell Terrier',
    'King Charles',
    'Komondor',
    'Labradoodle',
    'Labrador Retriever',
    'Lakeland Terrier',
    'Leonberger',
    'Lhasa Apso',
    'Lulu da Pomerânia',
    'Malamute do Alasca',
    'Maltês',
    'Mastife',
    'Mastim Napolitano',
    'Mastim Tibetano',
    'Norfolk Terrier',
    'Norwich Terrier',
    'Papillon',
    'Pastor Alemão',
    'Pastor Australiano',
    'Pinscher Miniatura',
    'Poodle',
    'Pug',
    'Rottweiler',
    'Sem Raça Definida (SRD)',
    'ShihTzu',
    'Silky Terrier',
    'Skye Terrier',
    'Staffordshire Bull Terrier',
    'Terra Nova',
    'Terrier Escocês',
    'Tosa',
    'Weimaraner',
    'Welsh Corgi (Cardigan)',
    'Welsh Corgi (Pembroke)',
    'West Highland White Terrier',
    'Whippet',
    'Xoloitzcuintli',
    'Yorkshire Terrier',
  ];
  racasGato = [
    'Abissínio',
    'Angorá',
    'Ashera',
    'Balinês',
    'Bengal',
    'Bobtail americano',
    'Bobtail japonês',
    'Bombay',
    'Burmês',
    'Burmês vermelho',
    'Chartreux',
    'Colorpoint de Pêlo Curto',
    'Cornish Rex.',
    'Curl Americano (sem informação)',
    'Devon Rex',
    'Himalaio',
    'Jaguatirica',
    'Javanês',
    'Korat',
    'LaPerm',
    'Maine Coon',
    'Manx',
    'Cymric',
    'Mau Egípcio',
    'Mist Australiano',
    'Munchkin',
    'Norueguês da Floresta',
    'Pelo curto americano',
    'Pelo curto brasileiro',
    'Pelo curto europeu',
    'Pelo curto inglês',
    'Persa',
    'Pixie-bob',
    'Ragdoll',
    'Ocicat',
    'Russo Azul',
    'Sagrado da Birmânia',
    'Savannah',
    'Scottish Fold',
    'Selkirk Rex',
    'Siamês',
    'Siberiano',
    'Singapura',
    'Somali',
    'Sphynx',
    'Thai',
    'Tonquinês',
    'Toyger',
    'Usuri',
  ];


  constructor() {}

  getRacasCachorros() {
    return this.racasCachorro;
  }

  getRacasGatos() {
    return this.racasGato;
  }
}
